version: '3.8'

services:
  backend:
    build:
      args:
        SPRING_PROFILES_ACTIVE: DOCKER
      context: "./StarWarsBack"
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=DOCKER
    ports:
      - "8080:8080"
 
  frontend:
    build:
      context: "./star-wars-app"
      dockerfile: ./Dockerfile
    ports:
      - "6969:80"
    depends_on:
      - backend